books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

people/urls.py
from django.urls import path
from people.views import PeopleView, PersonDetail, CreatePerson, UpdatePerson

app_name="people"

urlpatterns = [
  path("", PeopleView.as_view(), name="people"),
  path("<int:pk>", PersonDetail.as_view(), name="person"),
  path("<int:pk>/update", UpdatePerson.as_view(), name="update"),
  path("create", CreatePerson.as_view(), name="create"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
  path("create/<str:media_type>/<int:pk>", views.CreateReview.as_view(), name="create"),
  path("delete/<int:pk>", views.delete_review, name="delete"),
]

books/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Book(CoreModel):

  """ Book Model """

  title = models.CharField(max_length=120)
  year = models.IntegerField()
  cover_image = models.ImageField(null=True, blank=True)
  rating = models.FloatField()
  category = models.ForeignKey(
      "categories.Category", on_delete=models.CASCADE, related_name="books")
  writer = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="books")

  def __str__(self):
      return self.title

  def get_absolute_url(self):
    return reverse("books:book", kwargs={"pk": self.pk})

  class Meta:
    ordering = ["-created_at"]

books/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from books.models import Book


class BooksView(ListView):
  
  model = Book
  paginate_by = 18
  ordering = "-created_at"
  context_object_name = "books"

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['page_title'] = "All Books"
    return context


class BookDetail(DetailView):
  model = Book
  context_object_name = 'book'


class CreateBook(CreateView):
  model = Book
  fields = (
    "title",
    "year",
    "cover_image",
    "rating",
    "category",
    "writer",
  )


class UpdateBook(UpdateView):
  model = Book
  fields = (
    "title",
    "year",
    "cover_image",
    "rating",
    "category",
    "writer",
  )

templates/books/book_detail.html
{% extends "base.html" %}

{% block page_title %}
  {{book.title}}
{% endblock page_title %}

{% block content %}

<div class="mt-8 container mx-auto flex flex-col items-center">
    
    <div class="flex">
      <span class="font-normal text-xl block mr-1">{{book.title}}</span>
      <span class="text-sm text-gray-500 top-1">{{book.year}}</span>
    </div>

    <div class="w-1/5 h-104 shadow bg-cover bg-center rounded-lg my-6" style="background-image: url({{book.cover_image.url}});"></div>
    
    <div class="flex">
        <div class="w-4/5 overflow-hidden flex mr-2">
            <span class="uppercase font-medium text-xs border border-black text-black py-px px-1 mr-1.5">
                {{book.category}}
            </span>
        </div>
        <span class="text-sm flex items-center">
            <i class="fas fa-star text-red-500 text-xs mr-px"></i> 
            {{book.rating}}
        </span>
    </div>
    
    <div class="mt-4">Writer:
        <a href="{% url 'people:person' book.writer.pk %}" class="text-blue-400 hover:text-blue-600">{{book.writer}}</a>
    </div>

    <div class="flex mt-2 mb-6">
        <a class="bg-blue-400 hover:bg-blue-600 text-white py-2 px-4 rounded shadow" href="{% url 'books:update' book.pk %}">Edit Book</a>
        {% if user.is_authenticated %}
            {% include "mixins/fav_button.html" with obj=book kind='book' %}
        {% endif %}
    </div>

    {% if user.is_authenticated %}
        <form action="{% url 'reviews:create' 'book' book.pk %}" method="post" class="flex w-1/2 mb-8">
            {% csrf_token %}
            <input name="text" placeholder="Write a review..." class="mr-2 w-3/4 border" required />
            <select name="rating" required class="w-1/6 mr-2 border">
                <option value=1>1</option>
                <option value=2>2</option>
                <option value=3>3</option>
                <option value=4>4</option>
                <option value=5 selected>5</option>
            </select>
            <button class="bg-blue-400 hover:bg-blue-600 text-white py-2 px-4 rounded shadow">Submit</button>
        </form>
    {% endif %}

    <div class="flex flex-col items-start mb-8">
        {% if book.reviews %}
            {% for review in book.reviews.all %}
                <div class="flex">
                    {{review.created_by}}: 
                    {{review}}
                    {% with ''|center:review.rating as range %}
                    <span class="block ml-2 text-sm flex items-center">
                    {% for _ in range %}
                        <i class="fas fa-star text-red-500 text-xs mr-px"></i> 
                    {% endfor %}
                    </span>
                    {% endwith %}
                    {% if user.is_authenticated %}
                        {% if review.created_by == user %}
                            <a href="{% url 'reviews:delete' review.pk %}"><i class="fas fa-times ml-2 text-red-700"></i></a>
                        {% endif %}
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}
    </div>

</div>


{% endblock content %}

templates/books/book_form.html
{% extends "base.html" %}

{% block page_title %}
  Modify Book
{% endblock page_title %}

{% block content %}

  {% include 'mixins/form.html' with form=form cta="Save" %}

{% endblock content %}

templates/books/book_list.html
{% extends "base.html" %}

{% block page_title %}
  Books
{% endblock page_title %}

{% block content %}

<div class="container mx-auto">
    <div class="mt-8 px-5">
        <div class="text-center">
    	      <span class="text-3xl font-medium">Books</a>
        </div>
        <div class="grid grid-cols-6 gap-x-8 gap-y-16 -mx-24 mt-6 mb-16">
    	      {% for book in books %}
                {% include "mixins/book.html" with book=book %}
    	      {% endfor %}
        </div>
    </div>

    <div class="text-center font-medium mb-6">
        {% if page_obj.has_previous %}
            <a class="bg-blue-400 hover:bg-blue-600 text-white py-1 px-2 rounded" href="?page={{page_obj.previous_page_number}}"><i class="fas fa-chevron-left"></i></a>
        {% endif %}

        <span class="font-medium text-blue-600 mx-2">
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
        </span>

        {% if page_obj.has_next  %}
            <a class="bg-blue-400 hover:bg-blue-600 text-white py-1 px-2 rounded" href="?page={{page_obj.next_page_number}}"><i class="fas fa-chevron-right"></i></a>
        {% endif %}
    </div>
</div>

{% endblock content %}