books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

categories/urls.py
from django.urls import path
from categories.views import CategoryDetail

app_name="categories"

urlpatterns = [
  path("<int:pk>", CategoryDetail.as_view(), name="category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name="movies"

urlpatterns = [
  path("", MoviesView.as_view(), name="movies"),
  path("<int:pk>", MovieDetail.as_view(), name="movie"),
  path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
  path("create", CreateMovie.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from users.views import logout_view, LoginView, SignUpView, UserProfileView, UpdateProfileView, UpdatePasswordView

app_name = "people"

urlpatterns = [
    path("logout", logout_view, name="logout"),
    path("login", LoginView.as_view(), name="login"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("<int:pk>", UserProfileView.as_view(), name="profile"),
    path("update-profile/", UpdateProfileView.as_view(), name="update"),
    path("update-passwod/", UpdatePasswordView.as_view(), name="password"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
	<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
	<style>
		input, select {
			width: 100%;
			padding-left: 0.75rem;
			padding-right: 0.75rem;
			padding-top: 0.5rem;
			padding-bottom: 0.5rem;
    }

    .h-78 {
      height: 19.5rem;
    }

    .h-104 {
      height: 26rem;
    }

    html {
      background-color: #f7f8f9;
    }

    .top-1 {
      position: relative;
      top: 0.25rem;
    }

	</style>
	<title>{% block page_title %}{% endblock page_title %} | Nomad Media</title>
</head>

<body class="text-gray-800 font-light">
	{% include 'partials/header.html' %} {% block content %} {% endblock content %} {% include 'partials/footer.html' %}
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block page_title %}
  Home
{% endblock page_title %}

{% block content %}
<div class="container mx-auto">
<div class="my-8 px-5">
  <div class="flex items-center">
	  <a href="{% url 'movies:movies' %}" class="text-3xl text-blue-400 hover:text-blue-600">Movies</a> 
    <a href="{% url 'movies:create' %}"><i class="fas fa-plus text-xl text-blue-400 hover:text-blue-600 ml-2"></i></a>
  </div>
  <div class="grid grid-cols-6 gap-x-8 gap-y-16 -mx-24 mt-6 mb-16">
	  {% for movie in movies %}
      {% include "mixins/movie.html" with movie=movie %}
	  {% endfor %}
  </div>
</div>
	<hr />

<div class="my-8 px-5">
  <div class="flex items-center">
  <a href="{% url 'books:books' %}" class="text-3xl text-blue-400 hover:text-blue-600">Books</a>
  <a href="{% url 'books:create' %}"><i class="fas fa-plus text-xl text-blue-400 hover:text-blue-600 ml-2"></i></a>
  </div>
  <div class="grid grid-cols-6 gap-x-8 gap-y-16 -mx-24 mt-6 mb-16">
	{% for book in books %}
    {% include "mixins/book.html" with book=book %}
	{% endfor %}
  </div>
</div>
	<hr />

<div class="my-8 px-5">
  <div class="flex items-center">
	<a href="{% url 'people:people' %}" class="text-3xl text-blue-400 hover:text-blue-600">People</a> 
  <a href="{% url 'people:create' %}"><i class="fas fa-plus text-xl text-blue-400 hover:text-blue-600 ml-2"></i></a>
  </div>
  <div class="grid grid-cols-6 gap-x-8 gap-y-16 -mx-24 mt-6 mb-16">
	{% for person in people %}
	  {% include "mixins/person.html" with person=person %}
	{% endfor %}
  </div>
</div>
</div>
{% endblock content %}

templates/search.html
{% extends "base.html" %}

{% block page_title %}
  Search
{% endblock page_title %}

{% block content %}

<div class="container mx-auto">
    
    <form class="flex justify-center w-full my-8" method="GET"> 
      <input name="term" class="border rounded w-3/4 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Search Movie, Book or Person" />
      <button class="bg-blue-400 hover:bg-blue-600 text-white font-medium ml-2 py-2 px-4 rounded">Search</button>
    </form>

    <div class="block text-gray-700 text-center text-3xl font-medium mb-6">
        {% if term %}
            Results for "{{term}}"
        {% else %}
            Categories
        {% endif %}
    </div>

    {% if not term %}
        <div class="inline-block relative w-full flex flex-wrap my-5">
            {% for category in categories %}
            <div class="bg-orange-400 text-white px-5 shadow-md py-2 rounded-full mb-2 mr-2">
                <a href="{% url 'categories:category' category.pk %}">{{category.name}}</a>
            </div>
            {% endfor %}
        </div>
    {% endif %}

    <hr />

    {% if term %}
        <div class="my-8 px-5">
            <div class="text-center">
    	          <span class="text-3xl font-medium">Movies</span>
            </div>
            {% if not movies %}
                <div class="w-full text-center mt-6"><span>No Movies Found</span></div>
            {% else %}
                <div class="grid grid-cols-6 gap-x-8 gap-y-16 -mx-24 mt-6 mb-16">
                    {% for movie in movies %}
                        {% include "mixins/movie.html" with movie=movie %}
	                  {% endfor %}
                </div>
            {% endif %}
        </div>

        <hr class="w-full" />

        <div class="my-8 px-5">
            <div class="text-center">
    	          <span class="text-3xl font-medium">Books</span>
            </div>
            {% if not books %}
                <div class="w-full text-center mt-6"><span>No Books Found</span></div>
            {% else %}
                <div class="grid grid-cols-6 gap-x-8 gap-y-16 -mx-24 mt-6 mb-16">
                    {% for book in books %}
                        {% include "mixins/book.html" with book=book %}
	                  {% endfor %}
                </div>
            {% endif %}
        </div>

        <hr class="w-full" />

        <div class="my-8 px-5">
            <div class="text-center">
    	          <span class="text-3xl font-medium">People</span>
            </div>
            {% if not people %}
                <div class="w-full text-center mt-6"><span>No People Found</span></div>
            {% else %}
                <div class="grid grid-cols-6 gap-x-8 gap-y-16 -mx-24 mt-6 mb-16">
                    {% for person in people %}
                        {% include "mixins/person.html" with person=person %}
	                  {% endfor %}
                </div>
            {% endif %}
        </div>
    {% endif %}

</div>

{% endblock content %}