books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

categories/urls.py
from django.urls import path
from categories.views import CategoryDetail

app_name="categories"

urlpatterns = [
  path("<int:pk>", CategoryDetail.as_view(), name="category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name="movies"

urlpatterns = [
  path("", MoviesView.as_view(), name="movies"),
  path("<int:pk>", MovieDetail.as_view(), name="movie"),
  path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
  path("create", CreateMovie.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from users.views import logout_view, LoginView, SignUpView, UserProfileView, UpdateProfileView, UpdatePasswordView

app_name = "people"

urlpatterns = [
    path("logout", logout_view, name="logout"),
    path("login", LoginView.as_view(), name="login"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("<int:pk>", UserProfileView.as_view(), name="profile"),
    path("update-profile/", UpdateProfileView.as_view(), name="update"),
    path("update-passwod/", UpdatePasswordView.as_view(), name="password"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse



class User(AbstractUser):

    PREF_BOOKS = "books"
    PREF_MOVIES = "movies"
    PREF_CHOICES = ((PREF_BOOKS, "Books"), (PREF_MOVIES, "Movies"))

    LANG_EN = "english"
    LANG_KR = "korean"
    LANG_CHOICES = (
      (LANG_EN, "English"),
      (LANG_KR, "Korean")
    )

    bio = models.TextField()
    preference = models.CharField(
        max_length=20, choices=PREF_CHOICES, default=PREF_MOVIES)
    language = models.CharField(
        max_length=20, choices=LANG_CHOICES, default=LANG_EN)
    fav_book_cat = models.ForeignKey("categories.Category", on_delete=models.SET_NULL, null=True, related_name="book_users")
    fav_movie_cat = models.ForeignKey("categories.Category", on_delete=models.SET_NULL, null=True, related_name="movie_users")

    def __str__(self):
      return self.first_name
    
    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

users/forms.py
from django import forms
from users.models import User

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
from django.views import View
from django.views.generic import FormView, DetailView, UpdateView
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from users.forms import LoginForm, SignUpForm
from users.models import User


def logout_view(request):
    logout(request)
    return redirect(reverse("core:home"))


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, "users/login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse("core:home"))
        return render(request, "users/login.html", {"form": form})


class SignUpView(FormView):

    template_name = "users/signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class UserProfileView(DetailView):
    model = User
    context_object_name = "user_obj"


class UpdateProfileView(UpdateView):

    model = User
    template_name = "users/update_profile.html"
    fields = (
        "first_name",
        "last_name",
        "bio",
        "preference",
        "language",
        "fav_book_cat",
        "fav_movie_cat",
    )

    def get_object(self, queryset=None):
        return self.request.user



class UpdatePasswordView(PasswordChangeView):

    template_name = "users/update_password.html"

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
  Log In
{% endblock page_title %}

{% block content %}
    {% include 'mixins/form.html' with form=form cta="Log In" %}
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
  Sign Up
{% endblock page_title %}

{% block content %}
    {% include 'mixins/form.html' with form=form cta="Sign Up" %}
{% endblock content %}

templates/users/update_password.html
{% extends "base.html" %}

{% block page_title %}
  Change Password
{% endblock page_title %}

{% block content %}
    <div>
      {% include 'mixins/form.html' with form=form cta="Update Password" %}
    </div>
{% endblock content %}

templates/users/update_profile.html
{% extends "base.html" %}


{% block page_title %}
  Update Profile
{% endblock page_title %}

{% block content %}

    <div>
      {% include 'mixins/form.html' with form=form cta="Update Profile" %}
    </div>
    <div class="w-full text-center mb-6">
        <a href="{% url 'users:password' %}" class="text-blue-400 hover:text-blue-600 font-medium">Change Password</a>
    </div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
  {{user_obj.first_name}}'s Profile
{% endblock page_title %}

{% block content %}

<div class="mt-8 container mx-auto flex flex-col items-center">
    
    <span class="font-medium text-2xl block">{{user_obj.first_name}}</span>

    {% if user_obj.bio %}
      <span class="block mt-2">{{user_obj.bio}}</span>
    {% endif %}

    <span class="block mt-2 text-lg">{{user_obj.language|capfirst}}</span>

    <div class="mt-2">Prefer: 
        {% if user_obj.preference == 'movies' %}
            <a href="{% url 'movies:movies' %}" class="uppercase font-medium text-xs border border-black text-black py-px px-1 mr-1.5">
                {{user_obj.preference}}
            </a>
        {% else %}
            <a href="{% url 'books:books' %}" class="uppercase font-medium text-xs border border-black text-black py-px px-1 mr-1.5">
                {{user_obj.preference}}
            </a>
        {% endif %}
    </div>

    {% if user_obj.fav_book_cat %}
        <div class="mt-2">Fav. Book Category: 
            <a href="{% url 'categories:category' user_obj.fav_book_cat.pk %}" class="uppercase font-medium text-xs border border-black text-black py-px px-1 mr-1.5">
                {{user_obj.fav_book_cat}}
            </a>
        </div>
    {% endif %}
    {% if user_obj.fav_movie_cat %}
        <div class="mt-2">Fav. Movie Category: 
            <a href="{% url 'categories:category' user_obj.fav_movie_cat.pk %}" class="uppercase font-medium text-xs border border-black text-black py-px px-1 mr-1.5">
                {{user_obj.fav_movie_cat}}
            </a>
        </div>
    {% endif %}

    <a href="{% url 'users:update' %}" class="bg-blue-400 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded block mt-2 mb-6">Edit Profile</a>

</div>
    
{% endblock content %} 